Mmo/feat wallet observer
getsumer/sumer-sdk pull request #26
Opened 2023-05-31 09:21 UTC by cito-lito

2023-06-02 13:45 UTC, isaacdecoded requested changes
Looks good!

2023-06-02 13:45 UTC, isaacdecoded commented on src/observers/SumerObserver.ts
> +        _executionTarget[addressKey]
Do you think it can be simplified a bit? I don't know, maybe doing just:

`if (_executionTarget[walletKey] === true && _executionTarget[addressKey]) {}`

Just commenting, if you already visit other solutions and this is the one that best fit, ignore this one.

2023-06-12 10:37 UTC, isaacdecoded approved these changes

2023-06-14 15:26 UTC, isaacdecoded commented on src/models/index.ts
> +export * from '../observers/Transaction'
As I said before, it smells a bit, I mean: you are exporting a module from an outside scope, maybe this index.ts should be moved to /observers directory.

2023-06-14 17:53 UTC, isaacdecoded requested changes

2023-06-14 17:53 UTC, isaacdecoded commented on src/observers/TransactionObserver.ts
> +    if (this.isNotProcessed(execution.result)) {
What do you think about including this validation in the isTransation() method? So then we can find a way to remove the this.notifyService.trackTransaction() duplication.

2023-06-14 17:53 UTC, isaacdecoded commented on src/observers/TransactionObserver.ts
> +    // refactor needed:
What do you mean by this refactor comment? Is it what we talked about validating the complete list of transactions?

2023-06-14 17:53 UTC, isaacdecoded commented on src/observers/TransactionObserver.ts
> +    if (method === (Rpc_Methods.eth_sendTransaction || Rpc_Methods.eth_estimateGas)) {
At the end is this really necessary? Moreover, the line 94 returns the same that this validation scope.

2023-06-14 17:53 UTC, isaacdecoded commented on src/services/NotifyService.ts
> +  trackTransaction(
What do you think about including the _metadata_ and _error_ attributes in the Transaction model (interface)?

2023-06-14 17:53 UTC, isaacdecoded commented on src/services/NotifyServiceApi.ts
> +    body?: Transaction & { metadata: Parser.ParsedResult | Record<string, string> } & {
If we include the metadata and error as part of the Transaction interface we can avoid doing this types intersection.

2023-06-15 07:42 UTC, cito-lito commented on src/models/index.ts
> +export * from '../observers/Transaction'
lol, i gues i moved tx to the observers folder, dunno why really, was trying something, forgot to redo XD

2023-06-15 07:45 UTC, cito-lito commented on src/observers/TransactionObserver.ts
> +    if (this.isNotProcessed(execution.result)) {
hmm not_processed may not have a hash, dunno how atm, may we can discuss later

2023-06-15 07:45 UTC, cito-lito commented on src/observers/TransactionObserver.ts
> +    // refactor needed:
deleted

2023-06-15 07:46 UTC, cito-lito commented on src/observers/TransactionObserver.ts
> +    if (method === (Rpc_Methods.eth_sendTransaction || Rpc_Methods.eth_estimateGas)) {
jup, saw it, redoing

2023-06-15 09:01 UTC, cito-lito commented on src/services/NotifyService.ts
> +  trackTransaction(
done

2023-06-15 09:01 UTC, cito-lito commented on src/services/NotifyServiceApi.ts
> +    body?: Transaction & { metadata: Parser.ParsedResult | Record<string, string> } & {
oki

2023-06-15 09:02 UTC, cito-lito commented on src/observers/Transaction.ts
lol, i gues i moved tx to the observers folder, dunno why really, was trying something, forgot to redo XD

2023-06-20 14:32 UTC, isaacdecoded approved these changes

2023-06-20 14:39 UTC, merged